### ISSUE TITLE
how build connect?

### ISSUE THREAD

**Issue by lootoos** [minekube/connect#3]
what program will be required for the build?
what command should I enter for building?
does your program have a server + client?
is your program analogous to wireguard?

**Comment by robinbraemer** [comment]
You don't run this library, it is used e.g. by [Gate](https://github.com/minekube/gate/tree/master/pkg/util/connectutil).

As soon as Minekube Connect launches you can opt-in by enabling it in your [Gate config](https://github.com/minekube/gate/blob/e9eb15d0c66bee2f19d36e73e748613b99abd625/config.yml#L119) or installing one of the Java plugins for your server.

More information here: https://developers.minekube.com/connect/
